### ISSUE TITLE
Prepare plan/docs for customizing look&feel of CKAN

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/ckanext-c195#15]
The idea is to have @allyoucanmap do a first round of tests and docs to have a complete environment for standing up CKAN locally and start working on it to customize the L&F

@etj should be ready to help.

This will be fed to @luorlandini to start the real work on the look&feel.

**Comment by allyoucanmap** [comment]
## Steps

### ckan docker setup
- install docker (suggested steps to integrate with vscode https://code.visualstudio.com/docs/remote/containers#_installation)
- install a ckan instance locally with docker (steps from ckan documentation https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html)
- clone the ckan repository locally and checkout on the preferred version
```
cd /path/to/my/projects
git clone https://github.com/ckan/ckan.git
cd ckan
git checkout tags/ckan-2.9.2
```
- build and run ckan
```
cd contrib/docker
cp .env.template .env
docker-compose up -d --build
```
- navigate to localhost:5000 to interact with ckan
### add an extension inside docker of ckan (advice: use vscode to attach with a shell the container)
- clone the extension repository
```
cd /path/to/my/projects
git clone --recursive https://github.com/geosolutions-it/ckanext-c195

```
- to link ckan extension to ckan, create a file docker-compose.override.yml in /ckan/contrib/docker with the following code

```
cd /path/to/my/projects/ckan/contrib/docker 
touch  docker-compose.override.yml 

```
- copy this configuration in docker-compose.override.yml
```
version: '3'
services:
  ckan:
    volumes:
      - '../../../ckanext-c195:/usr/lib/ckan/venv/src/ckanext-c195'

```
- stop & start up the application  

```
docker-compose stop
docker-compose up -d

```
- get the id of the docker_ckan container with docker ps
```
docker ps
```
- attach the shell of the ckan docker container
```
docker exec -it {my_docker_ckan_id} bash
```
- activate the venv and navigate to the src folder inside the docker container
```
#this command have to run inside docker
source $CKAN_VENV/bin/activate && cd $CKAN_VENV/src/
```
- install the extension

```
#this command have to run inside docker 
cd ckanext-c195
pip install -e .
```
- install ckan dev requirements 
```
#this command have to run inside docker 
cd ../ckan
pip install -r dev-requirements.txt
```

- add the plugin to the production.ini config
```
#this command have to run inside docker 
vim /etc/ckan/production.ini
```
- append the name of plugin in the list and set debug equal true (both are in the file)
```
debug = true
....

ckan.plugins = stats text_view image_view recline_view c195
```
- detach from docker container bash shell and restart ckan docker
```
docker-compose restart ckan
```
### setup folder and files for the theme customization in the extension repository
- override base.html template, create a new file inside the extension folder `ckanext/c195/templates/base.html`
```html
{% ckan_extends %}

{% block styles %}
{# removed {{ super() }} because custom main.css is compiled directly from the ckan .less files and include all css rules #}
    <link rel="stylesheet" href="/base/css/main.css" />
{% endblock %}
```
- create a folder named base where manage all the *.css and *.less files
```
|-- ckanext/ (optional)
|    +-- c195/
|         +-- public/
|              +-- base/
|                   |-- css/
|                   |    +-- main.css (generated from less)
|                   |-- less/
|                   |    |-- custom.less
|                   |    |-- main.less
|                   |    +-- variable.less
|                   +-- package.json
|         +-- templates/
|                   +-- base.html
```
- main.less file should import the original them of ckan to simplify the override of variable
```less
@ckan-less-dir-path: "../../../../../../ckan/ckan/public/base/less/";
@import "@{ckan-less-dir-path}main.less";
@import "custom.less";
@import "variables.less";
```
- install node (https://github.com/nvm-sh/nvm) and then less
```
cd ckanext/c195/public/base
npm install less --save-dev
```
- add the script to create the main.css to package.json
```js
...,
"scripts": {
    "compile-css": "lessc -x less/main.less css/main.css"
},
...
```

----

The error from my previous comment was due to the missing install of dev-requirements.txt as suggested by @etj. We tried to add to the Dockerfile but without success, finally we were able to install it inside the docker container and make the docker installation work locally.

> I'm not so familiar with docker and took me some time to get an almost running installation but I have still some issues. I was able to setup the extension but the template does not update after the refresh of the page, changes where applied only with a complete restart of the ckan docker.
> I tried also to enable debug=true in the production.ini but then I got an error with dependencies(*).
> I tried also to add the missing dependency flask_debugtoolbar to requirements.txt of ckan and rebuild but without success.
> it's quite impossible to work with docker without the ability to update the pages to change some css or template.
> 
> @etj could you take a look on the steps?
> Note: the approach described below install the extension directly inside the container and assume that the changes will be applied directly in the container 
> 
> (*) error with debug equal true

```
db:5432 - accepting connections
ckan          | 2021-02-24 15:00:12,218 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
ckan          | 2021-02-24 15:00:12,220 INFO  [ckan.config.environment] Loading static files from public
ckan          | 2021-02-24 15:00:13,945 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | 2021-02-24 15:00:16,859 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan", line 11, in <module>
ckan          |     load_entry_point('ckan', 'console_scripts', 'ckan')()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 781, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
ckan          |     rest = Command.parse_args(self, ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
ckan          |     value = invoke_param_callback(self.callback, ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
ckan          |     return callback(ctx, param, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
ckan          |     ctx.obj = CkanCommand(value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
ckan          |     flask_app = make_flask_stack(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 143, in make_flask_stack
ckan          |     from flask_debugtoolbar import DebugToolbarExtension
ckan          | ImportError: No module named flask_debugtoolbar
```

**Comment by luorlandini** [comment]
We have a working environment with ckan and extension, so we can customize the theme.
I update the steps to recreate the enviroment, @allyoucanmap could you please take a look, if nothing is missing or unclear 
thanks

**Comment by simboss** [comment]
great.

**Comment by simboss** [comment]
@luorlandini I will put this in blocked so that you can move on with the real work as in  [this issue]([url](#15)) and then come back to this one and document the approach.

**Comment by allyoucanmap** [comment]
> I update the steps to recreate the enviroment, @allyoucanmap could you please take a look, if nothing is missing or unclear

thanks @luorlandini , I updated some steps after trying them and now it's working also on my Windows machine.
